---
- fail: msg="JAVA_HOME is not set!"
  when: lookup('env','JAVA_HOME') == ''

- name: Print Machine Hostname
  debug: var=ansible_ssh_host

- set_fact:
    jenkins_url: "http://{{ansible_ssh_host}}:{{jenkins_http_port}}"

- include: cli.yml
  tags: cli

- include: plugins.yml plugin_to_install={{item}}
  with_items:
    - "{{jenkins_plugins_list}}"
  tags: [cli,plugins]

- include: users.yml
  tags: [cli,users]
